# Generated by Django 2.1.7 on 2019-05-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pim_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_Code',
            new_name='product_Code',
        ),
    ]
